export const MOCK_MOVIES = [
  {
    adult: false,
    backdrop_path: '/srYya1ZlI97Au4jUYAktDe3avyA.jpg',
    genre_ids: [14, 28, 12],
    id: 238,
    original_language: 'en',
    original_title: 'The Godfather',
    overview:
      'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
    popularity: 198.299,
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    release_date: '1972-03-14',
    title: 'The Godfather',
    video: false,
    vote_average: 8.7,
    vote_count: 18534,
  },
  {
    adult: false,
    backdrop_path: '/5kI4jkLg4y5l3A8smAcO6U2M7JW.jpg',
    genre_ids: [28, 12, 878],
    id: 24428,
    original_language: 'en',
    original_title: 'The Avengers',
    overview:
      'When an unexpected enemy emerges that threatens global safety and security, Nick Fury, the director of the international peacekeeping agency known as S.H.I.E.L.D., finds himself in need of a team to pull the world back from the brink of disaster.',
    popularity: 108.098,
    poster_path: '/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg',
    release_date: '2012-04-25',
    title: 'The Avengers',
    video: false,
    vote_average: 7.7,
    vote_count: 24136,
  },
  {
    adult: false,
    backdrop_path: '/yEVnvn9bBXP0e9KpZ65PWf2n35K.jpg',
    genre_ids: [28, 12, 14],
    id: 671,
    original_language: 'en',
    original_title: "Harry Potter and the Philosopher's Stone",
    overview:
      "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers, he uncovers the truth about his parents' deaths.",
    popularity: 174.874,
    poster_path: '/wuMc08IPKEatf9rnMNXvIDxqP4W.jpg',
    release_date: '2001-11-16',
    title: "Harry Potter and the Philosopher's Stone",
    video: false,
    vote_average: 7.9,
    vote_count: 19879,
  },
  {
    adult: false,
    backdrop_path: '/1V1J63K2N1f5c32IFrs4F49qWGP.jpg',
    genre_ids: [28, 12, 14],
    id: 299536,
    original_language: 'en',
    original_title: 'Avengers: Infinity War',
    overview:
      'As the Avengers and their allies have continued to protect the world from threats too large for any one hero to handle, a new danger has emerged from the cosmic shadows: Thanos. A desolate world with a mission to collect all six Infinity Stones.',
    popularity: 134.679,
    poster_path: '/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg',
    release_date: '2018-04-25',
    title: 'Avengers: Infinity War',
    video: false,
    vote_average: 8.3,
    vote_count: 22121,
  },
  {
    adult: false,
    backdrop_path: '/spUazY1uxmCieAh8rzp2DGLc0l2.jpg',
    genre_ids: [18, 28, 80],
    id: 155,
    original_language: 'en',
    original_title: 'The Dark Knight',
    overview:
      'Batman raises the stakes in his war on crime. With the help of Lieutenant Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
    popularity: 179.487,
    poster_path: '/1hRoyzDtpgMU7Dz4JF22RANzQO7.jpg',
    release_date: '2008-07-16',
    title: 'The Dark Knight',
    video: false,
    vote_average: 8.5,
    vote_count: 24647,
  },
];
